bot:
  token: "XXXXXXXXXXXXXXXXXXXX"
  endpoint: ""
  media:
    delay: 5
  channel:
    enable: true
    id: ""
    filter: []
  private:
    enable: true
    sender: ""

log:
  home: "logs"
  file: "publisher.log"
  color: false
  local: false
  debug: true

publisher:
  type: "halo"

halo:
  host: "https://blog.mystery0.vip"
  token: "pat_XXXXXXXX"
  image:
    group: "attachment-group-XXXXXXXX"
    policy: "attachment-policy-XXXXXXXX"