bot:
  token: "{{telegram.bot.token}}"
  endpoint: ""

log:
  home: "logs"
  file: "publisher.log"
  color: false
  local: false
  debug: false

publisher:
  type: "halo"

halo:
  host: "{{halo.host}}"
  token: "{{halo.token}}"
  image:
    group: ""
    policy: "{{halo.image.policy}}"