bot:
  token: "XXXXXXXXXXXXXXXXXXXX"
  endpoint: ""
  channel: ""
  filter: []

log:
  home: "logs"
  file: "publisher.log"
  color: false
  local: false
  debug: false

publisher:
  type: "halo"

halo:
  host: "https://blog.mystery0.vip"
  token: "pat_XXXXXXXX"
  image:
    group: "attachment-group-XXXXXXXX"
    policy: "attachment-policy-XXXXXXXX"