name: Build With Docker
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  DOCKER_NAMESPACE: mystery0
  DOCKER_NAME: telegram-channel-publisher
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - name: 生成镜像Tag
        run: |
          version_name=`git rev-parse --short=4 HEAD`
          date=`date "+%Y%m%d"`
          docker_image_tag="${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_NAME }}:${date}-${version_name}"
          echo "docker_image_tag=$docker_image_tag" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: 登录仓库
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.docker_image_tag }}
